REASONING_MODEL: "Gemini" # "OpenAI" or "Gemini"
DOCUMENT_GENERATION_MODEL: "Gemini"

OPENAI_API_KEY: ""
GEMINI_API_KEY: ""

OPENAI_API_BASE: "https://api.openai.com/v1/chat/completions"
OPENAI_API_MODEL: "gpt-5"

OPENAI_API_WHISPER_URL: "https://api.openai.com/v1/audio/transcriptions"
OPENAI_WHISPER_MODEL: "whisper-1"

GEMINI_API_BASE: "https://generativelanguage.googleapis.com"
GEMINI_API_MODEL: "gemini-2.5-flash" # gemini-2.5-pro or gemini-2.5-flash-lite

MAX_COMPLETION_TOKENS: 500
TEMPERATURE: 1 # 1 for more creative responses, 0 for more precise responses
REQUEST_INTERVAL: 0.1  # Time in seconds between consecutive LLM requests

ANDROID_SCREENSHOT_DIR: "/sdcard"  # Set the directory on your Android device to store the intermediate screenshots. Make sure the directory EXISTS on your phone!
ANDROID_XML_DIR: "/sdcard"  # Set the directory on your Android device to store the intermediate XML files used for determining locations of UI elements on your screen. Make sure the directory EXISTS on your phone!

DOC_REFINE: false  # Set this to true will make the agent refine existing documentation based on the latest demonstration; otherwise, the agent will not regenerate a new documentation for elements with the same resource ID.
MAX_ROUNDS: 100  # Set the round limit for the agent to complete the task
DARK_MODE: false  # Set this to true if your app is in dark mode to enhance the element labeling
MIN_DIST: 10  # The minimum distance between elements to prevent overlapping during the labeling process
GRID_SIZE: 35 # 40 being a good grid size, 35 for phone, 43 for tablet(currently 47)
USE_SIMILARITY_COMPARISION: false
ENABLE_HUMAN_OVERRIDE: false
HUMAN_OVERRIDE_KEY: "|"
ENABLE_CHAT_INTERFACE: true

# Add these to config.yaml
PLATFORM: "android"  # "android" or "ios"

ANDROID_DEVICES: ["10BE8N1N5200203"]  # List of android device UDIDs

# iOS-specific settings (optional)
IOS_DEVICE_NAME: "Saurabh iPhone"
IOS_PLATFORM_VERSION: "26.0.1"
IOS_BUNDLE_ID: "com.ltfs.d2cApp"  # Optional
# IOS_BUNDLE_ID: "com.google.chrome.ios"
IOS_AUTO_LAUNCH: false
APPIUM_SERVER: "http://localhost:4723"
IOS_DEVICES: ["00008130-001268D80EBA001C"]  # List of iOS device UDIDs, or leave empty for auto-detection

ENABLE_VOICE: false
VOICE_TYPE: "Veena" # e.g. "Samantha", "Alex", "Ava", "Victoria", "Veena", "Rishi"
VOICE_SPEED: "185" # e.g. "170" (words per minute)

ALWAYS_GRID: true
DISABLE_XML: true

LOG_MODE: "dev"  # "dev" or "stage" or "prod"
